\version "2.20.0"
\language "english"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    \new Score
    <<
        \new Staff
        {
            g8
            fs8
            f8
            ef8
            r8
            f8
            f8
            af8
            e8
            fs8
            g8
            ef8
            r8
            f8
            fs8
            g8
            e8
            a8
            d8
            r8
            a8
            g8
            a8
            f8
            e8
            af8
            g8
            fs8
            r8
            af8
            g8
            fs8
            af8
            g8
            b8
            f8
            r8
            af8
            af8
            g8
            fs8
            bf8
            e8
            af8
            f8
            r8
            a8
            fs8
            af8
            bf8
            g8
            a8
            c'8
            cs'8
            af8
            b8
            f8
            fs8
            r8
            fs8
            d'8
            bf8
            c'8
            cs'8
            a8
            af8
            g8
            b8
            bf8
            f8
            r8
            af8
            c'8
            a8
            bf8
            fs8
            b8
            cs'8
            c'8
            g8
            bf8
            b8
            r8
            bf8
            d'8
            b8
            ef'8
            c'8
            a8
            bf8
            cs'8
            e'8
            b8
            af8
            g8
            d'8
            f8
            fs8
            r8
            a8
            bf8
            c'8
            c'8
            d'8
            b8
            a8
            af8
            cs'8
            a8
            bf8
            fs8
            g8
            ef'8
            c'8
            r8
            a8
            bf8
            b8
            d'8
            cs'8
            a8
            c'8
            ef'8
            bf8
            g8
            f'8
            af8
            b8
            e'8
            fs8
            r8
            cs'8
            c'8
            b8
            d'8
            a8
            cs'8
            e'8
            bf8
            ef'8
            af8
            fs'8
            c'8
            f'8
            d'8
            b8
            cs'8
            g8
            r8
            cs'8
            bf8
            d'8
            e'8
            c'8
            ef'8
            a8
            b8
            af8
            cs'8
            d'8
            f'8
            bf8
            cs'8
            g8
            fs'8
            e'8
            ef'8
            c'8
            r8
            f'8
            ef'8
            cs'8
            b8
            g'8
            fs'8
            bf8
            c'8
            d'8
            e'8
            a8
            cs'8
            ef'8
            af8
            f'8
            b8
            c'8
            d'8
            r8
            d'8
            ef'8
            b8
            cs'8
            d'8
            c'8
            e'8
            f'8
            g'8
            fs'8
            ef'8
            bf8
            a8
            af8
            b8
            d'8
            cs'8
            c'8
            e'8
            fs'8
            ef'8
            r8
            b8
            e'8
            d'8
            f'8
            ef'8
            b8
            fs'8
            cs'8
            a8
            g'8
            c'8
            e'8
            af'8
            d'8
            bf8
            ef'8
            f'8
            fs'8
            b8
            cs'8
            g'8
            e'8
            r8
            f'8
            d'8
            b8
            e'8
            ef'8
            c'8
            cs'8
            g'8
            fs'8
            d'8
            a'8
            f'8
            af'8
            e'8
            c'8
            bf8
            ef'8
            d'8
            b8
            cs'8
            g'8
            fs'8
            f'8
            r8
            ef'8
            d'8
            bf8
            e'8
            ef'8
            e'8
            c'8
            ef'8
            f'8
            cs'8
            g'8
            b8
            fs'8
            d'8
            af'8
            a'8
            e'8
            bf8
            ef'8
            c'8
            f'8
            cs'8
            r8
            ef'8
            ef'8
            fs'8
            c'8
            af'8
            f'8
            ef'8
            e'8
            g'8
            d'8
            cs'8
            ef'8
            b8
            a'8
            fs'8
            e'8
            bf'8
            af'8
            f'8
            c'8
            cs'8
            d'8
            ef'8
            r8
            af'8
            g'8
            f'8
            fs'8
            e'8
            ef'8
            a'8
            d'8
            f'8
            g'8
            af'8
            fs'8
            bf'8
            e'8
            cs'8
            c'8
            d'8
            b'8
            ef'8
            f'8
            a'8
            af'8
            fs'8
            g'8
            e'8
            r8
            f'8
            d'8
            e'8
            fs'8
            af'8
            c'8
            a'8
            bf'8
            g'8
            f'8
            ef'8
            d'8
            e'8
            fs'8
            b'8
            cs'8
            bf'8
            af'8
            a'8
            g'8
            f'8
            c'8
            e'8
            fs'8
            ef'8
            d'8
            cs'8
            r8
            g'8
            g'8
            d'8
            fs'8
            f'8
            a'8
            g'8
            e'8
            bf'8
            ef'8
            af'8
            c''8
            b'8
            fs'8
            f'8
            d'8
            cs'8
            a'8
            g'8
            e'8
            bf'8
            fs'8
            ef'8
            af'8
            b'8
            f'8
            cs'8
            r8
            fs'8
            g'8
            d'8
            bf'8
            g'8
            e'8
            b'8
            f'8
            af'8
            fs'8
            a'8
            g'8
            ef'8
            cs'8
            c''8
            bf'8
            d'8
            e'8
            b'8
            f'8
            fs'8
            a'8
            af'8
            g'8
            ef'8
            cs'8
            r8
            g'8
            e'8
            g'8
            a'8
            af'8
            d'8
            fs'8
            f'8
            b'8
            c''8
            bf'8
            g'8
            e'8
            ef'8
            af'8
            a'8
            cs''8
            f'8
            c''8
            g'8
            fs'8
            d'8
            bf'8
            b'8
            e'8
            ef'8
            af'8
            a'8
            f'8
            c''8
            r8
            g'8
            af'8
            b'8
            bf'8
            a'8
            cs''8
            g'8
            f'8
            c''8
            e'8
            b'8
            fs'8
            af'8
            bf'8
            ef'8
            a'8
            af'8
            d''8
            cs''8
            g'8
            c''8
            f'8
            b'8
            e'8
            bf'8
            fs'8
            af'8
            a'8
            r8
            af'8
            b'8
            g'8
            a'8
            cs''8
            bf'8
            f'8
            fs'8
            a'8
            ef'8
            c''8
            e'8
            af'8
            b'8
            g'8
            d''8
            bf'8
            f'8
            fs'8
            cs''8
            a'8
            c''8
            af'8
            ef'8
            b'8
            e'8
            g'8
            f'8
            bf'8
            d''8
            af'8
            fs'8
            r8
            bf'8
            a'8
            bf'8
            af'8
            g'8
            cs''8
            bf'8
            a'8
            c''8
            b'8
            f'8
            d''8
            fs'8
            a'8
            ef''8
            af'8
            g'8
            e'8
            bf'8
            cs''8
            c''8
            f'8
            b'8
            g'8
            a'8
            fs'8
            d''8
            af'8
            ef''8
            bf'8
            g'8
            b'8
            r8
            bf'8
            a'8
            af'8
            bf'8
            c''8
            g'8
            b'8
            f'8
            fs'8
            e'8
            d''8
            cs''8
            a'8
            bf'8
            af'8
            b'8
            c''8
            g'8
            ef''8
            f'8
            fs'8
            e'8
            b'8
            cs''8
            a'8
            bf'8
            af'8
            d''8
            c''8
            g'8
            a'8
            f'8
            r8
            bf'8
            b'8
            a'8
            ef''8
            g'8
            fs'8
            d''8
            c''8
            af'8
            cs''8
            bf'8
            b'8
            f'8
            a'8
            ef''8
            e''8
            c''8
            fs'8
            cs''8
            g'8
            d''8
            bf'8
            af'8
            a'8
            b'8
            f'8
            c''8
            bf'8
            cs''8
            ef''8
            e''8
            af'8
            r8
            b'8
            d''8
            cs''8
            ef''8
            bf'8
            af'8
            e''8
            a'8
            c''8
            g'8
            b'8
            cs''8
            fs'8
            d''8
            f''8
            ef''8
            af'8
            c''8
            bf'8
            a'8
            cs''8
            b'8
            e''8
            g'8
            ef''8
            c''8
            d''8
            fs'8
            af'8
            bf'8
            f''8
            b'8
            a'8
            cs''8
            r8
            e''8
            d''8
            cs''8
            bf'8
            b'8
            af'8
            a'8
            b'8
            cs''8
            ef''8
            c''8
            e''8
            g'8
            bf'8
            d''8
            a'8
            f''8
            b'8
            fs'8
            af'8
            cs''8
            c''8
            d''8
            ef''8
            bf'8
            a'8
            b'8
            g'8
            e''8
            cs''8
            af'8
            c''8
            f''8
            d''8
            fs'8
            b'8
            r8
            f''8
            ef''8
            a'8
            b'8
            bf'8
            c''8
            d''8
            cs''8
            a'8
            ef''8
            b'8
            af'8
            e''8
            bf'8
            f''8
            fs''8
            c''8
            g'8
            d''8
            cs''8
            a'8
            ef''8
            b'8
            bf'8
            e''8
            af'8
            d''8
            c''8
            f''8
            cs''8
            b'8
            ef''8
            a'8
            fs''8
            g'8
            e''8
            c''8
            bf'8
            r8
            cs''8
            c''8
            ef''8
            b'8
            c''8
            d''8
            a'8
            bf'8
            cs''8
            ef''8
            c''8
            e''8
            af'8
            f''8
            b'8
            d''8
            g'8
            fs''8
            bf'8
            a'8
            cs''8
            ef''8
            c''8
            af'8
            d''8
            b'8
            e''8
            f''8
            bf'8
            cs''8
            b'8
            g'8
            a'8
            c''8
            ef''8
            fs''8
            d''8
            e''8
            r8
            d''8
            b'8
            d''8
            ef''8
            bf'8
            d''8
            f''8
            c''8
            cs''8
            e''8
            b'8
            fs''8
            a'8
            g''8
            ef''8
            d''8
            af'8
            bf'8
            f''8
            c''8
            cs''8
            e''8
            fs''8
            ef''8
            b'8
            a'8
            d''8
            bf'8
            c''8
            f''8
            g''8
            af'8
            cs''8
            e''8
            ef''8
            b'8
            fs''8
            d''8
            bf'8
            a'8
            r8
            ef''8
            b'8
            fs''8
            cs''8
            d''8
            e''8
            f''8
            ef''8
            c''8
            cs''8
            b'8
            bf'8
            a'8
            ef''8
            af''8
            d''8
            g''8
            fs''8
            e''8
            f''8
            c''8
            cs''8
            b'8
            ef''8
            bf'8
            d''8
            f''8
            af''8
            a'8
            e''8
            fs''8
            g''8
            cs''8
            d''8
            c''8
            b'8
            ef''8
            e''8
            bf'8
            fs''8
            f''8
            r8
            e''8
            cs''8
            ef''8
            f''8
            e''8
            c''8
            ef''8
            d''8
            b'8
            g''8
            bf'8
            fs''8
            cs''8
            e''8
            af''8
            f''8
            d''8
            c''8
            a'8
            ef''8
            g''8
            b'8
            e''8
            bf'8
            cs''8
            fs''8
            f''8
            d''8
            c''8
            af''8
            e''8
            ef''8
            g''8
            cs''8
            a'8
            bf'8
            b'8
            d''8
            c''8
            r8
            e''8
            fs''8
            ef''8
            e''8
            f''8
            d''8
            g''8
            b'8
            af''8
            fs''8
            cs''8
            ef''8
            c''8
            e''8
            g''8
            f''8
            bf'8
            a''8
            d''8
            af''8
            e''8
            ef''8
            cs''8
            fs''8
            b'8
            c''8
            f''8
            g''8
            ef''8
            af''8
            fs''8
            d''8
            e''8
            bf'8
            a''8
            cs''8
            f''8
            c''8
            g''8
            b'8
            e''8
            r8
            ef''8
            e''8
            fs''8
            f''8
            d''8
            g''8
            af''8
            cs''8
            ef''8
            d''8
            c''8
            e''8
            f''8
            a''8
            fs''8
            b'8
            ef''8
            bf'8
            g''8
            cs''8
            af''8
            d''8
            f''8
            c''8
            e''8
            ef''8
            fs''8
            b'8
            a''8
            af''8
            cs''8
            f''8
            g''8
            d''8
            bf'8
            c''8
            e''8
            ef''8
            fs''8
            cs''8
            af''8
            r8
            f''8
            e''8
            ef''8
            g''8
            cs''8
            fs''8
            e''8
            a''8
            af''8
            d''8
            c''8
            f''8
            b'8
            g''8
            ef''8
            bf''8
            fs''8
            d''8
            e''8
            cs''8
            f''8
            g''8
            a''8
            af''8
            c''8
            fs''8
            ef''8
            e''8
            b'8
            f''8
            g''8
            d''8
            bf''8
            cs''8
            a''8
            af''8
            fs''8
            e''8
            ef''8
            c''8
            f''8
            g''8
            b'8
            d''8
            r8
            af''8
            g''8
            ef''8
            e''8
            fs''8
            f''8
            a''8
            af''8
            bf''8
            fs''8
            d''8
            ef''8
            g''8
            f''8
            b''8
            cs''8
            e''8
            c''8
            af''8
            a''8
            bf''8
            fs''8
            f''8
            g''8
            d''8
            ef''8
            b''8
            e''8
            cs''8
            af''8
            a''8
            c''8
            bf''8
            f''8
            g''8
            fs''8
            e''8
            d''8
            ef''8
            af''8
            b''8
            cs''8
            f''8
            a''8
            c''8
            fs''8
            r8
            fs''8
            af''8
            ef''8
            e''8
            f''8
            a''8
            d''8
            g''8
            cs''8
            af''8
            bf''8
            fs''8
            ef''8
            c''8
            e''8
            b''8
            f''8
            d''8
            fs''8
            a''8
            cs''8
            g''8
            af''8
            e''8
            bf''8
            ef''8
            a''8
            f''8
            d''8
            b''8
            c''8
            fs''8
            g''8
            af''8
            cs''8
            f''8
            ef''8
            bf''8
            e''8
            af''8
            a''8
            fs''8
            d''8
            g''8
            b''8
            f''8
            ef''8
            r8
            af''8
            ef''8
            fs''8
            af''8
            fs''8
            a''8
            g''8
            e''8
            f''8
            ef''8
            bf''8
            b''8
            d''8
            af''8
            c'''8
            g''8
            a''8
            cs''8
            fs''8
            f''8
            e''8
            ef''8
            a''8
            bf''8
            af''8
            b''8
            g''8
            d''8
            c'''8
            e''8
            fs''8
            f''8
            cs''8
            ef''8
            af''8
            a''8
            bf''8
            g''8
            b''8
            e''8
            c'''8
            d''8
            f''8
            fs''8
            ef''8
            r8
            e''8
            af''8
            a''8
            f''8
            bf''8
            fs''8
            af''8
            cs''8
            g''8
            c'''8
            e''8
            ef''8
            a''8
            d''8
            f''8
            b''8
            af''8
            fs''8
            bf''8
            g''8
            e''8
            ef''8
            a''8
            b''8
            cs''8
            f''8
            c'''8
            fs''8
            af''8
            d''8
            bf''8
            g''8
            e''8
            fs''8
            ef''8
            a''8
            f''8
            b''8
            cs''8
            af''8
            e''8
            c'''8
            d''8
            bf''8
            fs''8
            ef''8
            r8
            af''8
            fs''8
            f''8
            a''8
            bf''8
            e''8
            af''8
            b''8
            g''8
            fs''8
            ef''8
            d''8
            cs'''8
            c'''8
            f''8
            bf''8
            a''8
            e''8
            af''8
            fs''8
            g''8
            b''8
            ef''8
            f''8
            bf''8
            c'''8
            g''8
            a''8
            e''8
            cs'''8
            d''8
            af''8
            fs''8
            b''8
            f''8
            ef''8
            bf''8
            g''8
            a''8
            c'''8
            e''8
            af''8
            cs'''8
            fs''8
            f''8
            b''8
            d''8
            g''8
            a''8
            r8
            af''8
            f''8
            c'''8
            bf''8
            af''8
            c'''8
            g''8
            b''8
            fs''8
            f''8
            a''8
            bf''8
            cs'''8
            e''8
            d'''8
            af''8
            ef''8
            c'''8
            g''8
            fs''8
            b''8
            bf''8
            a''8
            f''8
            cs'''8
            af''8
            e''8
            g''8
            b''8
            fs''8
            c'''8
            d'''8
            bf''8
            ef''8
            a''8
            f''8
            e''8
            af''8
            g''8
            cs'''8
            bf''8
            c'''8
            a''8
            fs''8
            b''8
            f''8
            af''8
            d'''8
            ef''8
            g''8
            b''8
            r8
            af''8
            fs''8
            f''8
            af''8
            a''8
            bf''8
            g''8
            e''8
            b''8
            af''8
            bf''8
            c'''8
            d'''8
            cs'''8
            fs''8
            a''8
            ef''8
            b''8
            f''8
            g''8
            af''8
            e''8
            bf''8
            cs'''8
            fs''8
            b''8
            c'''8
            a''8
            f''8
            d'''8
            g''8
            af''8
            bf''8
            ef''8
            e''8
            b''8
            fs''8
            a''8
            c'''8
            cs'''8
            f''8
            af''8
            g''8
            d'''8
            bf''8
            fs''8
            a''8
            e''8
            f''8
            r8
            bf''8
            c'''8
            g''8
            af''8
            cs'''8
            bf''8
            a''8
            b''8
            c'''8
            af''8
            f''8
            d'''8
            fs''8
            g''8
            e''8
            bf''8
            ef'''8
            cs'''8
            a''8
            b''8
            af''8
            c'''8
            f''8
            g''8
            d'''8
            fs''8
            bf''8
            b''8
            a''8
            e''8
            cs'''8
            ef'''8
            af''8
            c'''8
            bf''8
            g''8
            fs''8
            f''8
            d'''8
            b''8
            a''8
            af''8
            cs'''8
            e''8
            bf''8
            c'''8
            g''8
            ef'''8
            bf''8
            fs''8
            d'''8
            af''8
            r8
            a''8
            fs''8
            b''8
            c'''8
            b''8
            bf''8
            g''8
            f''8
            af''8
            b''8
            a''8
            d'''8
            cs'''8
            e''8
            ef'''8
            fs''8
            bf''8
            c'''8
            af''8
            g''8
            b''8
            a''8
            f''8
            d'''8
            cs'''8
            bf''8
            fs''8
            g''8
            c'''8
            af''8
            e''8
            ef'''8
            a''8
            b''8
            d'''8
            f''8
            fs''8
            g''8
            bf''8
            cs'''8
            c'''8
            af''8
            a''8
            e''8
            ef'''8
            b''8
            bf''8
            fs''8
            d'''8
            g''8
            f''8
            r8
            fs''8
            c'''8
            bf''8
            fs''8
            af''8
            a''8
            b''8
            g''8
            cs'''8
            f''8
            bf''8
            c'''8
            e''8
            d'''8
            a''8
            fs''8
            af''8
            ef''8
            g''8
            b''8
            f''8
            bf''8
            cs'''8
            c'''8
            e''8
            a''8
            fs''8
            af''8
            fs''8
            d'''8
            g''8
            b''8
            bf''8
            ef''8
            f''8
            a''8
            fs''8
            c'''8
            e''8
            cs'''8
            af''8
            r8
            bf''8
            af''8
            a''8
            b''8
            bf''8
            fs''8
            f''8
            g''8
            c'''8
            e''8
            af''8
            a''8
            ef''8
            b''8
            bf''8
            cs'''8
            d''8
            f''8
            g''8
            fs''8
            af''8
            e''8
            a''8
            c'''8
            b''8
            ef''8
            bf''8
            f''8
            g''8
            cs'''8
            af''8
            e''8
            d''8
            fs''8
            a''8
            bf''8
            b''8
            f''8
            r8
            f''8
            fs''8
            bf''8
            e''8
            fs''8
            g''8
            ef''8
            f''8
            d''8
            a''8
            cs''8
            af''8
            bf''8
            g''8
            b''8
            fs''8
            c'''8
            e''8
            ef''8
            f''8
            a''8
            d''8
            af''8
            g''8
            fs''8
            e''8
            cs''8
            bf''8
            b''8
            a''8
            ef''8
            f''8
            c'''8
            d''8
            af''8
            g''8
            fs''8
            e''8
            a''8
            f''8
            bf''8
            d''8
            b''8
            g''8
            ef''8
            cs''8
            af''8
            c'''8
            fs''8
            e''8
            a''8
            f''8
            bf''8
            g''8
            af''8
            fs''8
            b''8
            d''8
            r8
            e''8
            e''8
            e''8
            f''8
            ef''8
            fs''8
            g''8
            d''8
            af''8
            cs''8
            f''8
            a''8
            c''8
            e''8
            bf''8
            b'8
            ef''8
            g''8
            fs''8
            af''8
            d''8
            e''8
            cs''8
            f''8
            a''8
            c''8
            ef''8
            fs''8
            g''8
            bf''8
            b'8
            e''8
            f''8
            a''8
            af''8
            d''8
            cs''8
            g''8
            ef''8
            fs''8
            c''8
            e''8
            bf''8
            f''8
            b'8
            a''8
            r8
            ef''8
            f''8
            fs''8
            e''8
            af''8
            ef''8
            c''8
            d''8
            cs''8
            fs''8
            b'8
            g''8
            f''8
            e''8
            ef''8
            a''8
            bf'8
            cs''8
            d''8
            af''8
            c''8
            f''8
            fs''8
            ef''8
            g''8
            e''8
            b'8
            d''8
            a''8
            r8
            d''8
            b'8
            e''8
            f''8
            d''8
            cs''8
            c''8
            ef''8
            bf'8
            g''8
            d''8
            fs''8
            af''8
            e''8
            b'8
            a'8
            f''8
            cs''8
            c''8
            ef''8
            d''8
            g''8
            e''8
            bf'8
            fs''8
            b'8
            f''8
            cs''8
            af''8
            ef''8
            d''8
            c''8
            a'8
            e''8
            f''8
            g''8
            b'8
            bf'8
            fs''8
            ef''8
            d''8
            cs''8
            f''8
            af''8
            r8
            b'8
            f''8
            c''8
            e''8
            fs''8
            a'8
            cs''8
            ef''8
            d''8
            b'8
            bf'8
            g''8
            f''8
            a'8
            e''8
            c''8
            af'8
            cs''8
            ef''8
            d''8
            fs''8
            b'8
            f''8
            bf'8
            e''8
            cs''8
            c''8
            g''8
            d''8
            ef''8
            af'8
            a'8
            fs''8
            cs''8
            b'8
            c''8
            f''8
            bf'8
            e''8
            d''8
            r8
            c''8
            cs''8
            d''8
            bf'8
            a'8
            cs''8
            f''8
            c''8
            b'8
            af'8
            ef''8
            g'8
            e''8
            d''8
            bf'8
            a'8
            fs'8
            cs''8
            c''8
            b'8
            ef''8
            f''8
            d''8
            af'8
            bf'8
            g'8
            e''8
            a'8
            c''8
            cs''8
            b'8
            ef''8
            fs'8
            bf'8
            d''8
            af'8
            f''8
            c''8
            g'8
            b'8
            e''8
            a'8
            cs''8
            ef''8
            bf'8
            af'8
            fs'8
            d''8
            c''8
            a'8
            f''8
            b'8
            e''8
            r8
            d''8
            g'8
            c''8
            b'8
            g'8
            a'8
            d''8
            af'8
            cs''8
            bf'8
            f'8
            c''8
            r8
            bf'8
            b'8
            bf'8
            cs''8
            af'8
            a'8
            f'8
            fs'8
            g'8
            cs''8
            a'8
            b'8
            c''8
            ef''8
            bf'8
            d''8
            e'8
            fs'8
            af'8
            f'8
            g'8
            a'8
            cs''8
            b'8
            c''8
            bf'8
            af'8
            ef''8
            fs'8
            g'8
            f'8
            d''8
            cs''8
            r8
            bf'8
            af'8
            fs'8
            g'8
            c''8
            bf'8
            f'8
            fs'8
            b'8
            a'8
            e'8
            af'8
            ef'8
            d''8
            g'8
            cs''8
            c''8
            a'8
            bf'8
            f'8
            af'8
            r8
            d'8
            f'8
            a'8
            af'8
            g'8
            ef'8
            e'8
            cs'8
            fs'8
            b'8
            bf'8
            d'8
            f'8
            af'8
            c''8
            a'8
            g'8
            cs'8
            ef'8
            fs'8
            bf'8
            e'8
            b'8
            f'8
            g'8
            af'8
            d'8
            c''8
            r8
            af'8
            f'8
            a'8
            g'8
            bf'8
            d'8
            f'8
            e'8
            fs'8
            af'8
            a'8
            ef'8
            cs'8
            c'8
            bf'8
            b'8
            g'8
            e'8
            f'8
            d'8
            fs'8
            af'8
            ef'8
            a'8
            cs'8
            d'8
            e'8
            bf'8
            f'8
            c'8
            g'8
            b'8
            fs'8
            af'8
            r8
            g'8
            ef'8
            cs'8
            g'8
            d'8
            c'8
            f'8
            e'8
            cs'8
            fs'8
            ef'8
            af'8
            a'8
            d'8
            bf'8
            ef'8
            e'8
            b8
            fs'8
            g'8
            f'8
            c'8
            cs'8
            a'8
            af'8
            ef'8
            d'8
            bf'8
            d'8
            e'8
            r8
            d'8
            f'8
            fs'8
            e'8
            ef'8
            bf8
            cs'8
            e'8
            c'8
            d'8
            f'8
            fs'8
            bf8
            g'8
            b8
            cs'8
            af'8
            a'8
            r8
            fs'8
            c'8
            ef'8
            cs'8
            fs'8
            e'8
            d'8
            ef'8
            f'8
            b8
            c'8
            cs'8
            bf8
            g'8
            af8
            d'8
            a8
            c'8
            e'8
            r8
            a8
            d'8
            e'8
            cs'8
            b8
            ef'8
            c'8
            cs'8
            b8
            g8
            bf8
            f'8
            e'8
            af8
            d'8
            r8
            bf8
            g8
            b8
            cs'8
            d'8
            a8
            bf8
            cs'8
            ef'8
            af8
            c'8
            e'8
            b8
            r8
            c'8
            b8
            bf8
            c'8
            cs'8
            g8
            a8
            a8
            ef'8
            d'8
            b8
            e'8
            af8
            bf8
            c'8
            fs8
            r8
            a8
            d'8
            f8
            g8
            a8
            c'8
            af8
            bf8
            g8
            cs'8
            fs8
            b8
            ef8
            e8
            a8
            r8
            f8
            ef8
            g8
            af8
            a8
            r8
            bf8
            g8
            fs8
            b8
            ef8
            e8
            af8
            f8
            g8
            d8
            r8
            ef8
            e8
            f8
            r8
        }
    >>
}