\version "2.20.0"
\language "english"

\header {
    tagline = ##f
}

\layout {}

\paper {}

\score {
    \new Score
    <<
        \new Staff
        {
            ef'4
            fs'4
            af'4
            cs'4
            b'4
            a'4
            bf'4
            f'4
            d'4
            g'4
            e'4
            af'4
            ef'4
            c'4
            fs'4
            cs'4
            b'4
            a'4
            bf'4
            f'4
            af'4
            g'4
            d'4
            e'4
            ef'4
            c'4
            fs'4
            cs'4
            bf'4
            f'4
            a'4
            b'4
            g'4
            d'4
            af'4
            cs'4
            ef'4
            e'4
            c'4
            fs'4
            bf'4
            f'4
            a'4
            g'4
            b'4
            d'4
            e'4
            af'4
            fs'4
            c'4
            cs'4
            f'4
            ef'4
            b'4
            bf'4
            a'4
            g'4
            fs'4
            af'4
            d'4
            e'4
            c'4
            ef'4
            cs'4
            f'4
            d'4
            b'4
            bf'4
            a'4
            fs'4
            af'4
            g'4
            ef'4
            e'4
            c'4
            cs'4
            bf'4
            d'4
            f'4
            b'4
            g'4
            a'4
            ef'4
            fs'4
            e'4
            af'4
            cs'4
            c'4
            d'4
            f'4
            b'4
            bf'4
            g'4
            ef'4
            fs'4
            e'4
            cs'4
            a'4
            c'4
            af'4
            f'4
            d'4
            g'4
            bf'4
            b'4
            ef'4
            fs'4
            e'4
            af'4
            cs'4
            a'4
            g'4
            c'4
            d'4
            f'4
            b'4
            bf'4
            ef'4
            fs'4
            a'4
            af'4
            cs'4
            e'4
            f'4
            c'4
            g'4
            bf'4
            ef'4
            d'4
            b'4
            af'4
            e'4
            fs'4
            a'4
            c'4
            cs'4
            f'4
            g'4
            bf'4
            ef'4
            d'4
            b'4
            af'4
            fs'4
            e'4
            a'4
            c'4
            cs'4
            f'4
            bf'4
            ef'4
            g'4
            d'4
            b'4
            e'4
            a'4
            fs'4
            af'4
            c'4
            cs'4
            bf'4
            f'4
            ef'4
            e'4
            d'4
            g'4
            b'4
            c'4
            cs'4
            fs'4
            af'4
            a'4
            bf'4
            ef'4
            f'4
            g'4
            d'4
            e'4
            b'4
            c'4
            cs'4
            af'4
            fs'4
            bf'4
            f'4
            a'4
            d'4
            ef'4
            g'4
            af'4
            b'4
            c'4
            e'4
            fs'4
            cs'4
            a'4
            d'4
            bf'4
            f'4
            ef'4
            g'4
            af'4
            cs'4
            b'4
            c'4
            e'4
            fs'4
            b'4
            a'4
            d'4
            f'4
            bf'4
            ef'4
            g'4
            cs'4
            af'4
            e'4
            fs'4
            c'4
            ef'4
            b'4
            a'4
            d'4
            f'4
            af'4
            bf'4
            cs'4
            g'4
            e'4
            b'4
            c'4
            fs'4
            ef'4
            a'4
            d'4
            f'4
            af'4
            e'4
            cs'4
            bf'4
            g'4
            d'4
            fs'4
        }
    >>
}